language: node_js
node_js:
  - "14"

services:
  - docker
  - postgresql

before_install:
  - docker ps -a
  - docker-compose up --build -d
  - docker build -t mercury/api .
  - docker run mercury/api /bin/sh -c "yarn run test"
