language: node_js
node_js:
  - "14"

services:
  - docker
  - postgresql

before_install:
  - docker-compose up --build -d
  - docker ps
  - docker run mercury-api_mercury-api /bin/sh -c "yarn run test"
